services:
  database:
    image: postgres:15-alpine
    container_name: smart-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: smart_lifecycle_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

  laravel-service:
    build:
      context: ../apps/laravel-service
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=smart_lifecycle_db
      - DB_USERNAME=admin
      - DB_PASSWORD=password123
    depends_on:
      - database

  frontend-service:
    build:
      context: ../apps/web-frontend
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - laravel-service
    volumes:
      - ../apps/web-frontend:/app
      - /app/node_modules # avoid the local node_modules to conflict with the container's

volumes:
  db_data: